# Static configuration
api:
  dashboard: true
  insecure: true

pilot:
  token: 11111111-1111-1111-1111-111111111111

log:
  level: DEBUG

experimental:
  localPlugins:
    azadjwtvalidation:
      moduleName: github.com/music-tribe/azadjwtvalidation

entryPoints:
  http:
    address: ":4000"
    forwardedHeaders:
      insecure: true

providers:
  file:
    filename: plugins-local/src/github.com/music-tribe/azadjwtvalidation/dynamic-dev-config.yml